title: OSGi.fx
logo: /assets/img/logo.png
description: An easy-to-use desktop application to manage OSGi frameworks remotely
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
jdeploy:
  url: https://www.jdeploy.com/~osgifx
agent:
  url: https://central.sonatype.com/artifact/com.osgifx/com.osgifx.console.agent/2.4.5
headless:
  url: https://central.sonatype.com/artifact/com.osgifx/osgifx/2.4.5
github_url: https://github.com/amitjoy/osgifx
